server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://1.15.228.108:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: fanfanService
    password: 123456